### ISSUE TITLE
Allow to pass separated values in suffixes 

### ISSUE THREAD

**Issue by thierryk** [yahoo/atomizer#81] opened 2015-03-10 22:26 UTC
I am thinking of how we could allow authors to create a rule like the one below by passing the value as a suffix:
```css
transition-delay: 2s, 4ms;
```

`.Trsde-<what should this be?>`

**Comment by renatoi** [comment] 2015-03-10 22:28
underscore. I think I wrote that, but not sure if we actually discussed it.

http://acss.io/guides/class-names.html

**Comment by thierryk** [comment] 2015-03-10 22:29
oh, I like "`_`" as it actually looks like a space inside the string. And yes, now I think I recall it was part of earlier debates about syntax.

**Comment by renatoi** [comment] 2015-03-10 22:32
Maybe we should remove the `start_t` example and give a better one such as the one you wrote here.

**Comment by src-code** [comment] 2015-03-12 18:46
This is a dupe of https://github.com/yahoo/atomizer/issues/88? 

How do we handle spaces vs commas in this case?

**Comment by src-code** [comment] 2015-04-08 18:08
Solved by switching to parenthesis syntax (eg `Trsde(2s,4ms)`)

**Closed by src-code** 2015-04-08 18:08 UTC
